### ISSUE TITLE
홈페이지 링크

### ISSUE THREAD

**Issue by DongjinLee2** [16-2-SKKU-OSS/16-2-OSS-B#14]
전부 다 새 탭으로 열게 하는 게 좋으려나

**Comment by jhyeok** [comment]
ㄴㄴ 내가 원하는 모양새는 새로운 html로 가는게 아니라
맨위에 네비게이션 바는 그대로 있고
밑에 화면만 바꾼는거

**Comment by jhyeok** [comment]
ㅈㅈ

**Comment by jhyeok** [comment]
# ㅈㅈ

**Comment by jhyeok** [comment]
**ㅈㅈ**

**Comment by jhyeok** [comment]
_ㅈㅈ_

**Comment by jhyeok** [comment]
또 원하는건
License
Let's study open-source
--------------------------------------
Mit Licence
GPL License
Apache License

여기까지 맨위 화면 라이센스 3개 클릭하면 밑으로 자동으로 드래그 되어서
네비게이션 역할하는거

**Comment by DongjinLee2** [comment]
외부 링크는 새 탭으로 열게 하고 License, Git/Github 이런 관련 탭 링크들은 니가 말한 식으로 하면 될 거 같은데

**Comment by jhyeok** [comment]
아 외부 링크는 새탭으로 하는게 좋을듯
