### ISSUE TITLE
최종 발표 관련

### ISSUE THREAD

**Issue by karlos1113** [16-2-SKKU-OSS/16-2-OSS-B#54]
먼저 모든 페이지에 슬라이드 적용 시켜서 커밋했구요
머지 되면 바로 확인 가능할거에요. 
그리고 예비군 출석 증빙으로 교수님께 문의드렸는데
발표는 발표 피피티 없이 깃헙에서 바로 발표하는게 좋다고하시고
저희는 홈페이지 위주다 보니까 홈페이지를 부각하는게 나을거 같다고 하시네요.
확인하시면 좋을거 같아서 올려요.

**Comment by jhyeok** [comment]
아 교수님이 그렇게 말씀하셨으면 그렇게 해야 겠네요

**Comment by karlos1113** [comment]
혹시해서 다시 메일로 문의드렸는데 맞다고 하시네요.
