### ISSUE TITLE
내일 오후에 같이 작업하실분 계신가요?

### ISSUE THREAD

**Issue by soong2hyung** [16-2-SKKU-OSS/16-2-OSS-B#60]
내일 오후 중 페이지 수정 학교에서 같이 하실분 계신가요?
시간은 언제든지 상관없습니다!
또는 내일 했으면 하는 수정 내용 생각나시는분은 여기 적어주세요!

**Comment by DongjinLee2** [comment]
저는 내일 시험이 있어서 못할 거 같습니다ㅠ

**Comment by karlos1113** [comment]
저 시간 되는데 혹시 어떤거 수정하실 생각이세요??

**Comment by soong2hyung** [comment]
인트로 페이지나 자잘하게 테마 같은것 수정 하지 않을까 싶습니다!

**Comment by soong2hyung** [comment]
컨텐츠 보충이나 작성되지 않은 파트도 일단 매꿔야하니 그것도 해야하지 않을까싶습니다

**Comment by karlos1113** [comment]
작성되지 않은 파트는 내일 발표라 내용 채워넣는건 사실 어쩔 수 없을 거 같아요ㅜㅜ 어짜피 발표시간에 지금 만들어놓은 것만 발표해도 충분할거 같기도 하구요.. 그리고 그 워드프레스 이미지 수정하신거 이미지 크기가 너무 작아서 그것만 먼저 업로드가 되더라구요(이따가 자세히 설명드릴게요), 그래서 다른걸로 수정해서 커밋했는데 혹시 이미지 별로시면 250kb이상 이미지로 바꿔주세요.
